apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: example-app1
  labels:
    app: example-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: ghcr.io/fayizk1/go-webapp-sample:deploy
        ports:
        - containerPort: 8080
