# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Test
        run: go test -v ./...

      - name: Build
        run: CGO_ENABLED=0  go build -v -o go-webapp-sample

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/fayizk1/go-webapp-sample:${{ github.sha }} 
            ghcr.io/fayizk1/go-webapp-sample:deploy
          
  update_image:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: fayizk1/cicd-config-try
          token: ${{secrets.GITHUB_TOKEN}}

      - name: install Kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      - run: ../../kustomize edit set image ghcr.io/fayizk1/go-webapp-sample:${{ github.sha }}
        working-directory: kustomize/argo

      - run: ../../kustomize build
        working-directory: kustomize/argo

      # - run: |
      #     git config user.email "gitops@example.com"
      #     git config user.name "gitops"
      #     git commit -am "Gitops updated image to ${{ github.sha }}"
      #     git pull --rebase
      #     git push
        
