
name: Actions Runner Controller Kubectl
on:
  push:
    branches: [ "master" ]

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: t803-runner-set
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
